name: 'GitHub woser'
 
on:
  push:
  schedule:
  # 定时任务，在每天的5点推送天气信息到邮箱
    - cron: '0 21 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    # 首先copy git仓库到虚拟机上
      - name: 'Woser codes'
        uses: twtctwte/woser@main
    # 执行仓库中的脚本文件
      - name: 'Get name'
        run: bash ./runfrompech.sh
